
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd complete
      #- mvn install -e
  post_build:
    commands:
      - echo Build completed on `date`
      - ls
      - mvn -f complete/pom.xml integration-test
artifacts:
  files:
    - complete/target/gs-spring-boot-0.1.0.jar
    - complete/scripts/*
    - complete/appspec.yml
  discard-paths: yes
reports:
  Java-Spring-Report: #surefire junit reports
    commands:
      - echo "Runnings tests..."
      - mvn -f pom.xml integration-test
    files:
      - '**/*'
    base-directory: 'complete/target/failsafe-reports'